apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-prod

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: prod
    includeSelectors: true

images:
  - name: kamloicc.jfrog.io/banking-docker-local/banking-demo/auth-service
    newTag: f989916efc9e
  - name: kamloicc.jfrog.io/banking-docker-local/banking-demo/account-service
    newTag: f989916efc9e
  - name: kamloicc.jfrog.io/banking-docker-local/banking-demo/transfer-service
    newTag: f989916efc9e
  - name: kamloicc.jfrog.io/banking-docker-local/banking-demo/notification-service
    newTag: f989916efc9e
  - name: kamloicc.jfrog.io/banking-docker-local/banking-demo/frontend
    newTag: f989916efc9e
