apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - data
  - auth
  - account
  - transfer
  - notification
  - gateway
  - frontend

labels:
  - pairs:
      app.kubernetes.io/part-of: banking-demo
    includeSelectors: true
