apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: transfer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transfer-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transfer-service
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: jfrog-registry
      containers:
        - name: transfer-service
          image: kamloicc.jfrog.io/banking-docker-local/banking-demo/transfer-service:f989916efc9e
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: 8003
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: banking-db-secret
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: banking-db-secret
                  key: REDIS_URL
            - name: CORS_ORIGINS
              value: "http://localhost:3000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: transfer-service
  labels:
    app.kubernetes.io/name: transfer-service
spec:
  selector:
    app.kubernetes.io/name: transfer-service
  ports:
    - name: http
      port: 8003
      targetPort: http
